USE [master]
GO

/****** Object:  Database [Geldverleih_Schule]    Script Date: 06/23/2012 14:25:09 ******/
CREATE DATABASE [Geldverleih_Schule] ON  PRIMARY 
( NAME = N'Geldverleih_Schule', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Geldverleih_Schule.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Geldverleih_Schule_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Geldverleih_Schule_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Geldverleih_Schule] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Geldverleih_Schule].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Geldverleih_Schule] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET ARITHABORT OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Geldverleih_Schule] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Geldverleih_Schule] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Geldverleih_Schule] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Geldverleih_Schule] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Geldverleih_Schule] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Geldverleih_Schule] SET  READ_WRITE 
GO

ALTER DATABASE [Geldverleih_Schule] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Geldverleih_Schule] SET  MULTI_USER 
GO

ALTER DATABASE [Geldverleih_Schule] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Geldverleih_Schule] SET DB_CHAINING OFF 
GO

